version: '3.7'
services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql-container
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:14-alpine
    container_name: postgresql-container
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  node:
    image: node:24-alpine
    container_name: node
    working_dir: /home/node/app
    ports:
      - '9999:9999'
    volumes:
      - ./gate-simulator:/home/node/app
    command: "npm start"